name: flutter_spinbox_fork
description: >-
  SpinBox is a numeric input widget with an input field for entering a specific value,
  and spin buttons for quick, convenient, and accurate value adjustments.
version: 0.4.0
homepage: https://github.com/NamSukio/flutter_spinbox
repository: https://github.com/NamSukio/flutter_spinbox

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  meta: ^1.3.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
